# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/heath/Study/Project/ENG5059P

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/heath/Study/Project/ENG5059P

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/heath/Study/Project/ENG5059P/CMakeFiles /home/heath/Study/Project/ENG5059P//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/heath/Study/Project/ENG5059P/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ecg_filter_demo

# Build rule for target.
ecg_filter_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ecg_filter_demo
.PHONY : ecg_filter_demo

# fast build rule for target.
ecg_filter_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecg_filter_demo.dir/build.make CMakeFiles/ecg_filter_demo.dir/build
.PHONY : ecg_filter_demo/fast

#=============================================================================
# Target rules for targets named CLDL

# Build rule for target.
CLDL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CLDL
.PHONY : CLDL

# fast build rule for target.
CLDL/fast:
	$(MAKE) $(MAKESILENT) -f DNF/CMakeFiles/CLDL.dir/build.make DNF/CMakeFiles/CLDL.dir/build
.PHONY : CLDL/fast

ecg_filter.o: ecg_filter.cpp.o
.PHONY : ecg_filter.o

# target to build an object file
ecg_filter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecg_filter_demo.dir/build.make CMakeFiles/ecg_filter_demo.dir/ecg_filter.cpp.o
.PHONY : ecg_filter.cpp.o

ecg_filter.i: ecg_filter.cpp.i
.PHONY : ecg_filter.i

# target to preprocess a source file
ecg_filter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecg_filter_demo.dir/build.make CMakeFiles/ecg_filter_demo.dir/ecg_filter.cpp.i
.PHONY : ecg_filter.cpp.i

ecg_filter.s: ecg_filter.cpp.s
.PHONY : ecg_filter.s

# target to generate assembly for a file
ecg_filter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecg_filter_demo.dir/build.make CMakeFiles/ecg_filter_demo.dir/ecg_filter.cpp.s
.PHONY : ecg_filter.cpp.s

ecg_filter_demo.o: ecg_filter_demo.cpp.o
.PHONY : ecg_filter_demo.o

# target to build an object file
ecg_filter_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecg_filter_demo.dir/build.make CMakeFiles/ecg_filter_demo.dir/ecg_filter_demo.cpp.o
.PHONY : ecg_filter_demo.cpp.o

ecg_filter_demo.i: ecg_filter_demo.cpp.i
.PHONY : ecg_filter_demo.i

# target to preprocess a source file
ecg_filter_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecg_filter_demo.dir/build.make CMakeFiles/ecg_filter_demo.dir/ecg_filter_demo.cpp.i
.PHONY : ecg_filter_demo.cpp.i

ecg_filter_demo.s: ecg_filter_demo.cpp.s
.PHONY : ecg_filter_demo.s

# target to generate assembly for a file
ecg_filter_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ecg_filter_demo.dir/build.make CMakeFiles/ecg_filter_demo.dir/ecg_filter_demo.cpp.s
.PHONY : ecg_filter_demo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CLDL"
	@echo "... ecg_filter_demo"
	@echo "... ecg_filter.o"
	@echo "... ecg_filter.i"
	@echo "... ecg_filter.s"
	@echo "... ecg_filter_demo.o"
	@echo "... ecg_filter_demo.i"
	@echo "... ecg_filter_demo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

